# Mettre basurl = "florian-dugat.ddns.net" quand sur serveur
# Sinon baseurl = "/"
baseurl = "http://florian.katech.net"
languageCode = "fr-fr"
title = "Portfolio Florian"
theme = "hugo-theme-hello-friend-ng-master"
DefaultContentLanguage = "fr"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

enableEmoji     = true

disqusShortname = "florian-dugat"


[author]
  name = "Florian Dugat"

#[taxonomies]
#  tag      = "tags"
#  category = ""


[params]
  AuthorName = "florian"
  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeSubtitle = "Bac+5 Expert systèmes et réseaux"

  [[params.social]]
     name = "email"
     url  = "mailto:dugat@intechinfo.fr"

  [[params.social]]
    name = "github"
    url  = "https://github.com/kasuke5"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/florian-dugat-99a3a9153/"

  [params.favicon]
  # you may want to use https://realfavicongenerator.net to generate you files
  # used in layouts/partials/head.favicon.html
  # relURL is applied to path
  enable    = true
  path      = "/images/favicons"
  version   = "1"
  maskIicon = "#5bbad5"
  tileColor = "#da532c"
  themeColor= "#ffffff"


  # Metadata mostly used in document's head
  description = "Homepage and blog by Florian Dugat"
  keywords =""
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  # contentTypeName = "projets"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.fr]
    title = "Florian DUGAT"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    [languages.fr.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.fr.params.navigation]
        help = "Aide"
  #[languages.fr.menu]
  #    [[languages.fr.menu.main]]
  #      identifier = "projets"
  #      name = "Projets"
  #      url = "/projets"
  #      weight = 1
      [[languages.fr.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = 3
#      [[languages.fr.menu.main]]
#        identifier = "Compétences"
#        name = "Compétences"
#        url = "/compétences"
#        weight = 4
      [[languages.fr.menu.main]]
        identifier = "A propos"
        name = "A propos"
        url = "about"
        weight = 4
      [[languages.fr.menu.main]]
        identifier = "experiences"
        name = "Expériences"
        url = "experience"
        weight = 2
      [[languages.fr.menu.main]]
          identifier = "realisations"
          name = "Réalisations"
          url = "realisations"
          weight = 1

  [languages.en]
    title = "Florian DUGAT"
    homeSubtitle = "System and network IT "
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "# cd /home/french"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projets"


# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
