baseurl = "/"
languageCode = "fr-fr"
title = "Portfolio Florian"
theme = "hugo-theme-hello-friend-ng-master"
DefaultContentLanguage = "fr"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

enableEmoji     = true

disqusShortname = "florian-dugat"


[author]
  name = "Florian Dugat"

[taxonomies]
  tag      = "tags"
  category = ""


[params]
  AuthorName = "florian"
  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeSubtitle = "Expert systèmes et réseaux"

  [[params.social]]
     name = "email"
     url  = "mailto:dugat@intechinfo.fr"

  [[params.social]]
    name = "github"
    url  = "https://github.com/kasuke5"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/florian-dugat-99a3a9153/"


  # Metadata mostly used in document's head
  description = "Homepage and blog by Florian Dugat"
  keywords = "homepage, blog, science, informatics, development, programming, portfolio, CV"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  # contentTypeName = "projets"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.fr]
    title = "Florian DUGAT"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    [languages.fr.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.fr.params.navigation]
        help = "Aide"
  [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = "projets"
        name = "Projets"
        url = "/projets"
        weight = 1
      [[languages.fr.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = 2
      [[languages.fr.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
        weight = 3

  [languages.en]
    title = "Hello Friend NG"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "hello friend ng"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"


# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"